extends Node
## 跨系统广播总线 —— autoload 单例，模块间解耦通信的唯一通道

@warning_ignore("unused_signal")
signal player_damaged(amount: int, current_hp: int)
@warning_ignore("unused_signal")
signal player_healed(amount: int, current_hp: int)
@warning_ignore("unused_signal")
signal player_died()
@warning_ignore("unused_signal")
signal player_fell(fall_distance: float)
@warning_ignore("unused_signal")
signal player_light_stumbled()
@warning_ignore("unused_signal")
signal player_unstable_stumbled(qte_window: float)
@warning_ignore("unused_signal")
signal player_recovery_qte_progress(progress: float, recovering: bool)
@warning_ignore("unused_signal")
signal player_fall_started()
@warning_ignore("unused_signal")
signal player_tumble_started()
@warning_ignore("unused_signal")
signal player_get_up_started(duration: float)
@warning_ignore("unused_signal")
signal player_balance_recovered()

@warning_ignore("unused_signal")
signal cane_hit_object(object_name: String, hit_point: Vector3, hit_normal: Vector3)
@warning_ignore("unused_signal")
signal cane_entered_npc_zone(npc_name: String)
@warning_ignore("unused_signal")
signal cane_exited_npc_zone(npc_name: String)

@warning_ignore("unused_signal")
signal touch_detected(hit_point: Vector3)

@warning_ignore("unused_signal")
signal npc_interaction_available(npc_name: String, prompt: String)
@warning_ignore("unused_signal")
signal npc_interaction_unavailable()
@warning_ignore("unused_signal")
signal npc_interaction_triggered(npc_name: String)

@warning_ignore("unused_signal")
signal game_state_changed(old_state: StringName, new_state: StringName)

@warning_ignore("unused_signal")
signal cutscene_started(cutscene_id: String)
@warning_ignore("unused_signal")
signal cutscene_ended(cutscene_id: String)

@warning_ignore("unused_signal")
signal audio_requested(sound_id: String, position: Vector3, volume_db: float)
